name: Publish package to GitHub Packages
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        project:
          - certmanager
          - cloudnative-pg
          - rabbitmq-operator
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@pulumi"
      - run: npm i
        working-directory: gen/${{ matrix.project }}
      - run: npm publish
        working-directory: gen/${{ matrix.project }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
